import { authOptions } from "@/pages/api/auth/[...nextauth]";
import "./globals.css";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import AppHeader from "@/components/AppHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader session={session} />

        {children}
      </body>
    </html>
  );
}
